# Generated by Django 5.0.3 on 2024-03-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_examinationquestion_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationquestion',
            name='answer',
            field=models.CharField(default='answer', max_length=2048),
            preserve_default=False,
        ),
    ]
