# Generated by Django 5.0.3 on 2024-03-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0003_examinationquestion_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='text',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='title',
            field=models.TextField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='examinationquestion',
            name='answer',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='examinationquestion',
            name='condition',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='examinationquestion',
            name='text',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='examinationquestion',
            name='title',
            field=models.TextField(max_length=1024),
        ),
    ]
