# Generated by Django 5.0.3 on 2024-03-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0004_alter_examination_text_alter_examination_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationquestion',
            name='answer',
            field=models.CharField(max_length=2048),
        ),
    ]
